// var phone_number="12345678901";
// var myNationality = "pakistani";
// var temperatureCelsius = "25.5";
// var populationDensity = "1000";
// var averageIncome ="50000";
// var distanceTraveled="120.75";
// var numberOfStudents = "2500";
// console.log ( populationDensity);
// console.log ( temperatureCelsius);
// console.log ( averageIncome);
// console.log ( distanceTraveled);
// console.log ( distanceTraveled);